# Generated by Django 5.2.4 on 2025-07-17 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='certificate',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='resume.certificatemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='education',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='resume.educationmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='experince',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='resume.experiencemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='linkedln',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='project',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='resume.projectmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='skills',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='resume.skillmodel'),
            preserve_default=False,
        ),
    ]
