# Generated by Django 5.2.4 on 2025-07-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profilemodel_certificate_profilemodel_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
