# Generated by Django 5.2.4 on 2025-07-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profilemodel_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='linkedln',
            new_name='linkedin',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='education',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='experince',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='project',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='skills',
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
