# Generated by Django 5.2.4 on 2025-07-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('mark', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('mark', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('summary', models.CharField(blank=True, max_length=50)),
                ('description1', models.CharField(blank=True, max_length=50)),
                ('description2', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=50)),
                ('github', models.CharField(blank=True, max_length=50)),
                ('description1', models.CharField(blank=True, max_length=50)),
                ('description2', models.CharField(blank=True, max_length=50)),
                ('techstack', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(blank=True, max_length=50)),
                ('framework', models.CharField(blank=True, max_length=50)),
                ('tools', models.CharField(blank=True, max_length=50)),
                ('soft_skill', models.CharField(blank=True, max_length=50)),
                ('linguistic', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
