# Generated by Django 5.2.4 on 2025-07-17 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_linkedln_profilemodel_linkedin_and_more'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatemodel',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='accounts.profilemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='accounts.profilemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='accounts.profilemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.profilemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillmodel',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='accounts.profilemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='description1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='description2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='summary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='description1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='description2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='github',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='techstack',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='framework',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='languages',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='linguistic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='soft_skill',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='tools',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
