# Generated by Django 5.2.4 on 2025-07-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_certificatemodel_profile_educationmodel_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatemodel',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
