# Generated by Django 5.2.4 on 2025-07-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_certificatemodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencemodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
