# Generated by Django 5.2.4 on 2025-07-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_experiencemodel_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencemodel',
            old_name='name',
            new_name='experience',
        ),
    ]
