# Generated by Django 5.2.4 on 2025-07-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_rename_name_experiencemodel_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificatemodel',
            old_name='mark',
            new_name='certificate',
        ),
        migrations.RenameField(
            model_name='educationmodel',
            old_name='name',
            new_name='education',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='heading',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='certificatemodel',
            name='name',
        ),
    ]
