# Generated by Django 5.2.4 on 2025-07-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_rename_date_certificatemodel_enddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='educationmodel',
            old_name='enddate',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='educationmodel',
            name='startdate',
        ),
    ]
