# Generated by Django 5.2.4 on 2025-07-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_rename_enddate_educationmodel_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificatemodel',
            old_name='enddate',
            new_name='first_cert_enddate',
        ),
        migrations.RenameField(
            model_name='certificatemodel',
            old_name='startdate',
            new_name='first_cert_startdate',
        ),
        migrations.RenameField(
            model_name='certificatemodel',
            old_name='certificate',
            new_name='first_certificate',
        ),
        migrations.RenameField(
            model_name='educationmodel',
            old_name='date',
            new_name='first_edu_date',
        ),
        migrations.RenameField(
            model_name='educationmodel',
            old_name='education',
            new_name='first_education',
        ),
        migrations.RenameField(
            model_name='educationmodel',
            old_name='mark',
            new_name='first_mark',
        ),
        migrations.RenameField(
            model_name='experiencemodel',
            old_name='description1',
            new_name='first_description1',
        ),
        migrations.RenameField(
            model_name='experiencemodel',
            old_name='description2',
            new_name='first_description2',
        ),
        migrations.RenameField(
            model_name='experiencemodel',
            old_name='enddate',
            new_name='first_exp_enddate',
        ),
        migrations.RenameField(
            model_name='experiencemodel',
            old_name='startdate',
            new_name='first_exp_startdate',
        ),
        migrations.RenameField(
            model_name='experiencemodel',
            old_name='experience',
            new_name='first_experience',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='description1',
            new_name='first_description1',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='description2',
            new_name='first_description2',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='github',
            new_name='first_github',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='project',
            new_name='first_project',
        ),
        migrations.RenameField(
            model_name='projectmodel',
            old_name='techstack',
            new_name='first_techstack',
        ),
        migrations.AddField(
            model_name='certificatemodel',
            name='fourth_cert_enddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='certificatemodel',
            name='fourth_cert_startdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='certificatemodel',
            name='fourth_certificate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='certificatemodel',
            name='second_cert_enddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='certificatemodel',
            name='second_cert_startdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='certificatemodel',
            name='second_certificate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='certificatemodel',
            name='third_cert_enddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='certificatemodel',
            name='third_cert_startdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='certificatemodel',
            name='third_certificate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='second_edu_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='second_education',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='second_mark',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='second_description1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='second_description2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='second_exp_enddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='second_exp_startdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='second_experience',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='second_description1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='second_description2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='second_github',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='second_project',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='second_techstack',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
