# Generated by Django 5.2.4 on 2025-07-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_rename_enddate_certificatemodel_first_cert_enddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificatemodel',
            old_name='first_cert_enddate',
            new_name='first_cert_date',
        ),
        migrations.RenameField(
            model_name='certificatemodel',
            old_name='first_cert_startdate',
            new_name='fourth_cert_date',
        ),
        migrations.RenameField(
            model_name='certificatemodel',
            old_name='fourth_cert_enddate',
            new_name='second_cert_date',
        ),
        migrations.RenameField(
            model_name='certificatemodel',
            old_name='fourth_cert_startdate',
            new_name='third_cert_date',
        ),
        migrations.RenameField(
            model_name='educationmodel',
            old_name='first_edu_date',
            new_name='first_edu_enddate',
        ),
        migrations.RenameField(
            model_name='educationmodel',
            old_name='second_edu_date',
            new_name='first_edu_startdate',
        ),
        migrations.RemoveField(
            model_name='certificatemodel',
            name='second_cert_enddate',
        ),
        migrations.RemoveField(
            model_name='certificatemodel',
            name='second_cert_startdate',
        ),
        migrations.RemoveField(
            model_name='certificatemodel',
            name='third_cert_enddate',
        ),
        migrations.RemoveField(
            model_name='certificatemodel',
            name='third_cert_startdate',
        ),
        migrations.RemoveField(
            model_name='educationmodel',
            name='first_education',
        ),
        migrations.RemoveField(
            model_name='educationmodel',
            name='second_education',
        ),
        migrations.RemoveField(
            model_name='experiencemodel',
            name='first_experience',
        ),
        migrations.RemoveField(
            model_name='experiencemodel',
            name='second_experience',
        ),
        migrations.RemoveField(
            model_name='experiencemodel',
            name='summary',
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='first_college',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='first_degree',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='second_college',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='second_degree',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='second_edu_enddate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='educationmodel',
            name='second_edu_startdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='first_exp_place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='first_exp_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='first_summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='second_exp_place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='second_exp_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='second_summary',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='certificatemodel',
            name='first_certificate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='certificatemodel',
            name='fourth_certificate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='certificatemodel',
            name='second_certificate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='certificatemodel',
            name='third_certificate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='first_mark',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='educationmodel',
            name='second_mark',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='first_description1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='first_description2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='second_description1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='second_description2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='first_description1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='first_description2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='first_github',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='first_project',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='first_techstack',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='second_description1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='second_description2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='second_github',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='second_project',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='second_techstack',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='framework',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='languages',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='linguistic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='soft_skill',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='tools',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
